### ISSUE TITLE
Configurable max length of the presented results

### ISSUE THREAD

**Issue by pywkm** [fisadev/ulauncher-better-file-browser#2]
Hi, thanks for cool extension! :)

Please add configurable max length of the result list. Without it long result list (i.e. after just `"f d"` or even `"f "` typed) causes that Ulauncher window goes out of the screen and stays there. :(
It's probably because I have two monitors configuration in a lying `T` shape (main is horizontal, side one is vertical with top edge placed above edge of the horizontal one. I'm attaching screen captures to show what I mean. 
I know this is Ulauncher bug, but still, I don't see a reason for displaying 10+ results after typing just one letter - instead of going on that list with arrows or selecting item with `alt-<letter>` it's so much easier to just type next letter and make that list shorter).

![screenshot_2019-09-06 20-11-01](https://user-images.githubusercontent.com/7727739/64451063-b4252e80-d0e3-11e9-88d9-e9e275c10a56.jpg)
![screenshot_2019-09-06 20-11-57](https://user-images.githubusercontent.com/7727739/64451062-b4252e80-d0e3-11e9-88f6-05e499610bb1.jpg)

**Comment by fisadev** [comment]
Good idea!

Already done and pushed, you can update it and configure the limit. I also added another option to control whether hidden files are shown or not :)

**Comment by pywkm** [comment]
Thanks, works like a charm! ;) And delivery time was also impressive. :)
