### ISSUE TITLE
Weird highlighting within results

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [fisadev/ulauncher-better-file-browser#8]
Extension version: 2019-9-6
Ulauncher 5.15.2

Please see this image:

![image](https://github.com/fisadev/ulauncher-better-file-browser/assets/47056543/a429590e-dfc8-4634-82f7-4bffa801b3cb)

Why are some letters bolder/whiter than others? Are the highlighted letters the ones that appear within the navigated path? If so, why on earth do that highlighting? :)

**Comment by fisadev** [comment]
Hi! That's an artifact of how ulauncher works, as the full current text (in this case, the path) is used to highlight the "matching" items below, using full fuzzy matching logic. The internal code of the extension knows to only filter items based on the last bit of the path, but the ulauncher UI doesn't know about that, so it uses the full path as source of letters to highlight in the listed items. Sorry! But honestly I don't know of a way of preventing that just from the code in the extension I developed, I think this would require changing a bit of ulauncher itself.

**Comment by LinuxOnTheDesktop** [comment]
Right. That's unfortunate but liveable-with. Thank you for the information. You might want to close this issue.
